name: Infra DevOps Pack CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: ESLint
        run: pnpm lint
      - name: Prettier
        run: pnpm format:check

  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.x
      - name: Terraform fmt
        run: terraform fmt -check -recursive iac
      - name: Terraform init
        run: terraform -chdir=iac init
      - name: Terraform validate
        run: terraform -chdir=iac validate

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/actionlint@v1
